[package]
name = "r-lanscan"
version = "0.1.0"
edition = "2021"

[lib]
name = "r_lanscan"
path = "src/lib/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.16", features = ["derive"] }
pcap = "1.1.0"
