[workspace]
resolver = "2"
members = ["cli", "lib", "term"]
package.license  = "GPL-3.0-or-later"
package.keywords = ["network", "network-scanner", "network-scanning", "ARP", "SYN"]
package.edition = "2024"
