[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2024"
homepage = "https://github.com/robgonnella/r-lanscan"
repository = "https://github.com/robgonnella/r-lanscan"
license = "MIT OR Apache-2.0"
keywords = ["ARP", "SYN", "network-scanner", "packet", "port-scanner"]

[workspace.dependencies]
serde_json = "^1.0"
