[env]
# auto-load .env file into environment (like direnv)
_.file = ".env"

# rust automatically configured from rust-toolchain.toml

[settings]
idiomatic_version_file_enable_tools = ["rust"]

[hooks]
postinstall = """
if ! cargo llvm-cov --help >/dev/null 2>&1; then
  cargo install cargo-llvm-cov
fi
if ! cargo machete --help >/dev/null 2>&1; then
  cargo install cargo-machete
fi
"""
