name: releasaurus 🦕
description: Runs releasaurus to automate release process
inputs:
  repo:
    description: The github repo to affect
    default: ${{ github.server_url }}/${{ github.repository }}
  token:
    description: The github token to use. This token will need privileges to create PRs, tags, labels, and releases
    default: ${{ github.token }}
  clone_depth:
    description: Sets the clone depth for the target repository. Set to 0 to clone all history
    default: "250"
  debug:
    description: Enables debug logs
    default: "false"
outputs: {}
runs:
  using: docker
  image: robgonnella/releasaurus:v0.2.0
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.token }}
    - ${{ inputs.clone_depth }}
    - ${{ inputs.debug }}
  entrypoint: |
    REPO="$1"
    TOKEN="$2"
    CLONE_DEPTH="$3"
    DEBUG="$4"
    args=""
    if [ "${DEBUG}" = "true" ]; then
      args="--debug"
    fi
    releasaurus release --github-repo ${REPO} --github-token ${TOKEN} --clone-depth ${CLONE_DEPTH} ${args}
    releasaurus release-pr --github-repo ${REPO} --github-token ${TOKEN} --clone-depth ${CLONE_DEPTH} ${args}
