name: releasaurus 🦕
description: Runs releasaurus to automate release process
inputs:
  repo:
    description: The github repo to affect
    default: ${{ github.server_url }}/${{ github.repository }}
  token:
    description: The github token to use. This token will need privileges to create PRs, tags, labels, and releases
    default: ${{ github.token }}
  clone_depth:
    description: Sets the clone depth for the target repository. Set to 0 to clone all history
    default: "250"
  debug:
    description: Enables debug logs
    default: "false"
  git_user_name:
    description: The git user name to use when committing and creating tags
    default: "ReleasaurusCI"
  git_user_email:
    description: The git user email to use when committing and creating tags
    default: releasaurus-ci@noreply.com
outputs: {}
runs:
  using: docker
  image: Dockerfile
