name: analyze

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  machete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-rust
        with:
          cache-shared-key: analyze
          cache-policy: pull
      - name: Run cargo machete
        run: cargo machete

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-rust
        with:
          cache-shared-key: analyze
          cache-policy: pull-push
      - name: lint
        run: cargo clippy --all-targets --all-features -- -D warnings

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-rust
        with:
          cache-shared-key: analyze
          cache-policy: pull
      - name: doc
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --no-deps --workspace

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-rust
        with:
          cache-shared-key: analyze
          cache-policy: pull
      - name: fmt
        run: cargo fmt --all --check
