name: R_LANSCAN

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Modify the rust toolchain version
        run: rustup override set 1.89.0
      - name: Output cargo version
        run: cargo --version
      - name: Build
        run: cargo build --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Modify the rust toolchain version
        run: rustup override set 1.89.0
      - name: Output cargo version
        run: cargo --version
      - name: Add clippy component
        run: rustup component add clippy
      - name: Lint
        run: cargo clippy --all-targets --all-features

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: modify the rust toolchain version
        run: rustup override set 1.89.0
      - name: Output cargo version
        run: cargo --version
      - uses: taiki-e/install-action@v2
        with:
          tool: rustfmt
      - name: fmt
        run: cargo fmt -- --all --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Modify the rust toolchain version
        run: rustup override set 1.89.0
      - name: Output cargo version
        run: cargo --version
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - name: Test
        run: script -q /dev/null -c "cargo llvm-cov"
