name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        include:
          - cmd: script -q /dev/null -c 'cargo test'
            os: ubuntu-latest
          - cmd: script -q /dev/null cargo test
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-rust
        with:
          cache_policy: pull
      - name: Test
        run: ${{ matrix.cmd }}
